persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type all

listener 8883
protocol mqtt

cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/mqtt-broker.crt
keyfile /mosquitto/certs/mqtt-broker.key

allow_anonymous true
